### ISSUE TITLE
MTB knihovna - 2 chyby

### ISSUE THREAD

**Issue by aprochaz** [kmzbrnoI/mtb-lib#2]
1. Pokud je knihovna připojena a program je ukončen bez zastavení knihovny (například pád programu), pak při příštím použití se nelze připojit metodou start (metoda open proběhne). Po restartu kolejiště opět funguje i metoda start.
2. Po vypnutí Window Formu (C#), ve kterém je knihovna používána, vyskočí chybové hlášení:
   Exception EOSError in module MTB.dll at 00011F71.
   System Error. Code: 1400.
   Neplatný popisovač okna.

Používán OS Windows 7.

**Comment by malinajan** [comment]
1. asi nevyřeším bez změny FW MTB-USB modulu, což je v současnosti nereálné, 2. kouknu na to v nejbližší době ...

**Comment by malinajan** [comment]
Voláš při ukončení aplikace `Unload`?
Nastává tato chyba v `Unload`, nebo někde jinde?

**Comment by malinajan** [comment]
Mělo by být vyřešeno v příštím releasu, zásadně překopána logika fungování knihovny a doplněna dokumentace na wiki (branch new-interaface).
